# Generated by Django 2.2.1 on 2019-06-28 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('harvest_date', models.DateTimeField(verbose_name='date of last harvest')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_page_url', models.CharField(max_length=200)),
                ('last_modification_date', models.DateTimeField(verbose_name='date of last modification')),
                ('json_ld', models.CharField(max_length=1000)),
                ('metadata_url', models.CharField(max_length=200)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d1webdemo.Site')),
            ],
        ),
    ]
