# Generated by Django 2.2.1 on 2019-06-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d1webdemo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='json_ld',
            field=models.CharField(max_length=10000),
        ),
    ]
