name: slendernode38
channels:
  - conda-forge
dependencies:
  - aiohttp=3.6.1
  - asn1crypto=1.2.0
  - async-timeout=3.0.1
  - atomicwrites=1.3.0
  - attrs=19.3.0
  - ca-certificates=2019.9.11
  - certifi=2019.9.11
  - cffi=1.13.2
  - chardet=3.0.4
  - contextlib2=0.6.0.post1
  - cryptography=2.8
  - entrypoints=0.3
  - html5lib=1.0.1
  - icu=64.2
  - idna=2.8
  - importlib_metadata=0.23
  - iso8601=0.1.12
  - isodate=0.6.0
  - keepalive=0.5
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=9.0.0
  - libcxxabi=4.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgfortran=4.0.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libxml2=2.9.10
  - libxslt=1.1.33
  - llvm-openmp=9.0.0
  - lxml=4.4.2
  - more-itertools=7.2.0
  - multidict=4.5.2
  - ncurses=6.1
  - numpy=1.17.3
  - openssl=1.1.1d
  - owlrl=5.2.1
  - packaging=19.2
  - pandas=0.25.3
  - pip=19.3.1
  - pluggy=0.13.1
  - py=1.8.0
  - pyasn1=0.4.8
  - pycodestyle=2.5.0
  - pycparser=2.19
  - pyflakes=2.1.1
  - pyjwt=1.7.1
  - pyopenssl=19.0.0
  - pyparsing=2.4.5
  - pyshacl=0.11.3.post1
  - pysocks=1.7.1
  - pytest=5.3.1
  - python=3.8.0
  - python-dateutil=2.8.1
  - python-json-logger=0.1.11
  - pytz=2019.3
  - pyxb=1.2.6
  - rdflib=4.2.2
  - rdflib-jsonld=0.4.0
  - readline=8.0
  - requests=2.22.0
  - requests-mock=1.7.0
  - setuptools=42.0.1
  - six=1.13.0
  - sparqlwrapper=1.8.2
  - sqlite=3.30.1
  - tk=8.6.10
  - urllib3=1.25.7
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - xz=5.2.4
  - yarl=1.3.0
  - zipp=0.6.0
  - zlib=1.2.11
  - pip:
    - aioresponses==0.6.1
    - dataone-cli==3.4.7
    - dataone-common==3.4.7
    - dataone-libclient==3.4.7
    - dataone-scimeta==3.4.7
    - requests-toolbelt==0.9.1
    - zipstream==1.1.4
